CREATE TABLE IF NOT EXISTS facebook (
    `LATITUDE` FLOAT (48) NOT NULL,
    `LONGITUDE` FLOAT (48) NOT NULL,
    `ZIP` VARCHAR (255),
    `UNDER_FIVE` FLOAT (48),
    `SIXTY_MORE` FLOAT (48),
    `MEN` FLOAT (48),
    `WOMEN` FLOAT (48),
    `WOMEN_15_49` FLOAT (48),
    `YOUTH_15_24` FLOAT (48),
    `POPULATION` FLOAT (48),
    PRIMARY KEY (`LATITUDE`, `LONGITUDE`)
);